### ISSUE TITLE
Tor-by-default in breadwallet?

### ISSUE THREAD

**Issue by eragmus** [voisine/breadwallet#226] opened 2015-07-05 00:13 UTC
Hi, I think I've mentioned this before, but it may have been overshadowed by my other suggestions.

I'd like to re-introduce the idea of Tor support, in the context of some implementations I've noticed by apps on iOS that already do have Tor support right now.

ChatSecure, as of version 3.0 on Jan. 5, 2015, has had Tor support. See here: https://chatsecure.org/blog/chatsecure-ios-v3-released/
> "Right now (to my knowledge) we are the only messaging app on the App Store that supports Tor. Although the current implementation appears to be functional, please only use it for testing purposes until it has been studied further by security professionals. In other words, do not rely on it for strong anonymity, and use something like TAILS instead.

> During our journey to add Tor support, we first tried to extract the Tor management code from Mike Tigas’s Onion Browser, but discovered it was too tightly coupled with the rest of the app. We also investigated Tor.framework by Hive Wallet but it required some awkward patching of the Tor source code, and has since been deprecated by the original developers. Eventually we discovered Claudiu-Vlad Ursache’s CPAProxy, a more modern attempt at a thin Objective-C wrapper around Tor’s control port. Although it is currently missing a few features like customizable bridges and pluggable transports (and a security audit), I would encourage other developers who are interested in adding Tor support to their iOS apps to help us improve CPAProxy."

Relevant links:
- https://github.com/chatsecure/onionkit
- https://github.com/ChatSecure/Tor.framework
- https://github.com/ursachec/CPAProxy
- https://github.com/ChatSecure/CPAProxy

Downsides of Tor support in breadwallet:
- Slow Tor speed --> This would seem to be an issue only when syncing the wallet, not when receiving transactions or sending transactions to the network. So, is it possible to sync the wallet with the network without Tor (I don't imagine any identifying data is sent during the sync, or am I wrong?), but use Tor for the other purposes?

----

On another note, how does breadwallet encrypt its data, if at all, or does it only rely on iPhone's encrypted storage? I ask because of ChatSecure's notes on 'encrypted storage', where they say:
> When ChatSecure iOS v2.0 was released over a year ago, it contained a major overhaul of the internal data model to support Core Data, Apple’s solution for data persistence. We originally planned on utilizing the MITRE Corporation’s encrypted-core-data project, which adds a customized NSPersistentStoreCoordinator backed by Zetetic’s SQLCipher. Unfortunately working with Core Data can be terribly frustrating, especially when you cannot debug its closed-source internals.

> Fortunately we discovered YapDatabase by Robbie Hanson, an Objective-C key-value-collection store built on top of sqlite. It has all sorts of nice features like a coherent concurrency model, fast full text search, easy binding to UITableView, and more. If you develop iOS apps, I strongly encourage you to check it out, especially in conjunction with something like Mantle. Because it is built on top of sqlite, it was relatively straightforward for us to add SQLCipher support (use the YapDatabase/SQLCipher Cocoapods subspec).

> "all content is locally encrypted in a SQLCipher database"

Can, or should, the same approach be used to better encrypt breadwallet data on iOS?

**Comment by voisine** [comment] 2015-07-07 08:51
Thanks for suggesting CPAProxy, I haven't looked at it before.

re: encrypted data - we use the keychain for the most sensitive private key material which is hardware encrypted using the secure enclave. It's backed up but can only be decrypted using the original device it was backed up from. Your transaction history uses standard iOS "data protection" which is also strongly encrypted, but can be decrypted with access to your iCloud account/password.

dupe of #178

**Closed by voisine** 2015-07-07 08:51 UTC
