### ISSUE TITLE
Request: Various small things

### ISSUE THREAD

**Issue by mike15623** [voisine/breadwallet#320] opened 2015-12-12 14:30 UTC
Aloha breadwallet developers! 

Sweet wallet, thanks for a simple app that does what it does *well*.
I have a few (hopefully new) ideas:

1. Past transaction dollar amounts that **do not** vary with todays exchange rate
  - If I sent my buddy $50 a week ago, I want to look in my transaction list and see it as $50, not $63

2. Annotate transfers - allow user to tag transfers with custom labels
  - A date and an amount isn't enough (for me) to remember a particular transaction

3. Export transaction history as an xls/csv/xml file
  - I'd probably never use it, but it seems like a good idea

4. Custom background image/color
  - The grey is a little basic

5. Bitcoin exchange value on home page
  - 1BTC = $XXX.XX  Why not utilize some of that blank space?

6. Other bitcoin denominations
  - I just like to see my account as bitcoin, not as bits or whatever

Okay, I hope those aren't sore points or anything.  Just some things I though would be nice.
Mahalo!

**Comment by voisine** [comment] 2015-12-16 22:07
@mike15623 thanks for the feedback!

I think 1) is a good idea, at least on the transaction details page. This could be provided using a historical exchange rate API, or recorded as metadata once we have a way to keep a backup of that in case you need to recover on another device.

2) is a dupe of issue #86, we need a way to store/recover encrypted transaction metadata since right now you can only recover information stored in the blockchain.

You'll be happy to know that you can do 3) already. Type bread://addresslist into the mobile safari URL bar. It will launch breadwallet and ask if you want to copy a list of your bitcoin addresses to the clipboard. You can then import this list into bitcoin accounting software.

4) We are working with a designer for the next update :)

5) I'm not too sure about, feels like something we might add to the tx history instead. I really like all the clean negative space, minimalist design for send/receive.

6) is a dupe of #299

**Comment by mike15623** [comment] 2015-12-21 00:48
Thanks for addressing all of my ideas!

#1 & #2 are interesting.  There is no way to store encrypted text using the blockchain?  Or maybe it's that there are none that would follow ␢read's policies?  What about giving users the *option* to store encrypted metadata on a cloud sever (iCloud/Dropbox/etc)?  Anyways, good luck on that task.  Sounds like it might open a few options for you.

#3 & #4 - cool!

#5 - Maybe the BTC exchange rate could reside in the top bar? It would have the same (or maybe less) visual impact as showing the the balance.

Having my balance always showing (once TX history is checked) is kind of a security concern as it should be private.  It should only be visible in the TX page.

The BTC exchange rate could occupy the top bar in the send and receive portions.  It's generic, informational and appropriate to the task of sending or receiving BTC.

#6 - I understand where you guys are coming from on this one.  One full bitcoin is already too large as a primary currency unit.  You are making a push for a smaller denomination as the common term.  No problem.  Make it the default for ␢read, but still offer a choice.

The semantics of bitcoin will change organically.  No need to force the change, just be ready with options and a flexible client.  Who knows, maybe the market will (irrationally) decide on a unit that is one decimal place higher or lower than your choice.  Just my two ␢'s!


I appreciate the time it takes for responses,
Thanks again!

**Comment by mike15623** [comment] 2015-12-21 00:52
Sorry didn't realize the "#" was going to automatically link to existing issues...

The numbers in my last post are for this thread only.

**Comment by voisine** [comment] 2015-12-21 01:46
You can store data in the blockchain but not enough to be useful for this purpose. The transaction fees would be prohibitively expensive. iCloud would work, but it's not cross platform and not everyone has an iCloud account. We plan to provide that service ourselves.

As far as having configurable options, that makes the product more confusing and doesn't help the community arrive at a single standard. It's pretty clear at this point that it will be uBTC but if not, we can release an app update. I don't feel like we're pushing anyone to do anything, just offering the best product we can with an eye towards the long term.

**Comment by klauslovgreen** [comment] 2016-01-10 10:40
Trezor is offering data through encrypted files to dropbox (maybe option of Google Drive, iCloud and Dropbox?)

**Comment by voisine** [comment] 2016-01-10 18:05
iCloud now has CloudKit JS which allows web apps access, so I suppose that can be used from any platform. The problem with all these services is that they are tied to a username/password, and they likely have counter measures in place to prevent an app from auto-creating accounts with random username/password derived from something like a wallet seed. The user would actually have to choose and then sign-up for or login to one of these services. I'm hoping for a user experience like today where you only provide a recovery phrase and everything just gets restored.

**Closed** 2016-02-24 00:00 UTC
