### ISSUE TITLE
feature request: option to display on bits or btc

### ISSUE THREAD

**Issue by abgit** [voisine/breadwallet#383] opened 2016-06-21 16:42 UTC
Hi guys,

Would be great if we could be able to choose between `bits` or `BTC` when displaying bitcoin values (on balance and transactions history).

We can choose our local currency (for conversions) but we cannot change `bits` to `btc`.

What do you think?

best,
FA

**Comment by voisine** [comment] 2016-06-21 17:13
This is a dupe of #299 

We're building breadwallet with the goal of gaining mass adoption for bitcoin. Two important things to achieve that will be 1) a single denomination that the bitcoin community standardizes on 2) a standard denomination that doesn't require understanding arbitrary precision decimals.

The bits standard has two decimal places like most other currencies in the world, and once the community switches it won't need to be changed again even if bitcoin were to replace all other existing currencies, and bits are already a larger denomination right now than several currencies used by 100's of millions of people every day. It also keeps the app simpler with fewer confusing options for new users to bitcoin. 

I understand it's annoying right now when most others haven't switched yet, but the more popular the app becomes, the more incentive we create to help other bitcoin apps and services make the switch.

**Closed by voisine** 2016-06-21 17:13 UTC
Labels: duplicate
