### ISSUE TITLE
mBTC?

### ISSUE THREAD

**Issue by kwolk** [voisine/breadwallet#364] opened 2016-04-18 05:20 UTC
Please could you make it easier to send smaller amounts (as in BitCoin Core with mBTC) as the mobile wallet will likely be used to make payments without scanning a QR code and smaller amounts are more common, which is what mBTC is good for.

**Comment by voisine** [comment] 2016-04-18 05:30
breadwallet uses "bits". 1,000,000 bits = 1 bitcoin

duplicate of #299

**Closed by voisine** 2016-04-18 05:30 UTC
Labels: duplicate
