### ISSUE TITLE
Possible key derivation bug & fund loss

### ISSUE THREAD

**Issue by adiabat** [voisine/breadwallet#437] opened 2017-07-24 17:43 UTC
Hi - I'm not 100% on this bug and don't mean to cause undue alarm, but the recent code changes may have introduced a bug in key derivation which leads to invalid addresses being shown to the user.

The address `14p5cGy5DZmtNMQwTQiytBvxMVuTmFMSyU` has recently had a number of bitcoin sent to it.  This is the hash of compressed pubkey `21000000000000000000000000000000000000000000000000000000000000000000ac` which is not a real pubkey, but seems like software may generate this if the private key is a null pointer or 0 or something.

I have seen this address displayed on breadwallet for android today (not my phone, could be malware or some other problem), and the start of sends to this on the blockchain match up with recent changes to the breadwallet code changes.  This is a pretty serious problem as a couple bitcoins have been sent to that address and are lost.  I didn't have time to use the affected phone by the guy who showed it to me said he was surprised because breadwallet reported him having coins as soon as he installed and synced.

I haven't had time to look through the code and this may not be a breadwallet problem at all, but in case it is, a quick check for the 14p5cGy... address, which causes the whole app to crash immediately if it ever sees it, would protect users from any problem while this is figured out.  The problem may be intermittent & hard to find but it can't hurt to block that address.  I will meet back with the guy who has the affected phone & app tomorrow and can check other things if there are questions.  

Hope this can be of help and if it's not breadwallet hope we can find & stop the losses quickly.

**Comment by voisine** [comment] 2017-07-24 17:49
Thanks for the report. This is the github repo for the iOS app, so I'll close this issue, but we're investigating for the android app over at github.com/breadwallet/breadwallet-android

**Closed by voisine** 2017-07-24 17:49 UTC

**Comment by adiabat** [comment] 2017-07-24 17:54
Ah sorry, yes I saw this only on the android app, may not affect iOS.

**Comment by fivepiece** [comment] 2017-07-24 18:10
Just to add to @adiabat 's report, the hash160 is actually of `0x000000000000000000000000000000000000000000000000000000000000000000` .  Seems like the complete blob is a pay-to-pubkey script.

**Comment by voisine** [comment] 2017-07-24 18:22
yes you get 14p5cGy5DZmtNMQwTQiytBvxMVuTmFMSyU from base58check(0 + ripemd160(sha256(0x000000000000000000000000000000000000000000000000000000000000000000)))

I added some sanity checks to make sure even a memory corruption issue will never generate this address just to be safe. We're also trying duplicate the issue on our end, haven't been able to just yet.

**Comment by voisine** [comment] 2017-07-24 20:03
@fivepiece @adiabat we have a new android beta build that has some additional checks. I don't know if either of you can consistently reproduce the problem, but if so, please try the new beta build and let me know if the issue is still there.

you can opt-in to the beta here: https://play.google.com/apps/testing/com.breadwallet
wait until it shows "(beta)" in the play store and download the update

**Comment by fivepiece** [comment] 2017-07-24 20:42
Sorry @voisine , I haven't tried breadwallet myself yet.  @adiabat raised my awareness to this issue and I thought it's worth to nit pick at the actual hash value in case it might be important to for testing.  Hopefully access to the affected device could reveal more.
