### ISSUE TITLE
Lost transactions???? 

### ISSUE THREAD

**Issue by lesserorc** [voisine/breadwallet#136] opened 2015-01-18 13:28 UTC
From my Breadwallet I made two transfers of .18 btc total at around 10am on January 17th. I noticed the transactions came up under recent history. But after a few hours and the withdrawal not processing the transaction disappeared. It does not come up under history even after syncing and re-syncing to blockchain. Can you help me figure this out ? I know I sent it to right address. And it's weird that it doesn't show up under history anymore. And when i put in address (that i was to recieve the btc) to blockchain explorer nothing comes up. Other transactions do but not the two I'm talking about. I have sentto this address from my breadwallet before and had no problems. Help!?

**Comment by voisine** [comment] 2015-01-18 17:24
Now that you've resynced and verified that the transactions didn't go through with a block explorer, you can try to resend. If there was a transaction missing from the wallet when you tried to send the first time, it could have been rejected as a double spend of the one missing.

**Comment by lesserorc** [comment] 2015-01-18 23:25
I guess I didn't make that clear enough. The btc is gone from my wallet. 

Phil's Doo-hickie

**Comment by voisine** [comment] 2015-01-19 00:25
Not sure I understand. You had a balance in your wallet, you sent it, the transactions after a while disappeared from the wallet and are not visible in block explorers, but the funds are still gone? If that's all correct, can you go over your transaction history and see if everything adds up?

**Comment by lesserorc** [comment] 2015-01-19 02:33
These are screenshots of my breadwallet history. I have not run the numbers yet but I figured two heads is better than one. :) I will send you any other info that relates to this. Thank you for your time. 

Phil's Doo-hickie

**Comment by voisine** [comment] 2015-01-19 06:20
I think you forgot to attach the screenshots, but my guess is that you may have had less in the wallet than what it initially said because of a missing transaction. When you spend it, it was rejected as a double spend and so got removed from the wallet and doesn't show in block explorers. After doing a rescan, the missing transaction was added and now you're seeing the actual balance.

I've made improvements so missing transactions are less likely to happen.

**Comment by lesserorc** [comment] 2015-01-19 09:15
Screenshots ?? I hope.






Phil's Doo-hickie

**Comment by voisine** [comment] 2015-01-19 10:01
Sorry, don't see any screenshots. When I add an image to a comment it creates a link to a cloud.githubusercontent.com url. Your comments don't contain any links.

**Comment by dabura667** [comment] 2015-01-19 10:14
@lesserorc Just FYI you can't post screenshots via e-mail posting. You have to log into github and actually dragging and dropping them into the post box.

**Comment by voisine** [comment] 2015-01-26 09:35
gonna close this out. @lesserorc feel free to re-open if you find an issue with your balance. I suspect there was a spend missing from the wallet that was corrected by a rescan. There are several improvements in master that make this situation less likely to occur.

**Closed by voisine** 2015-01-26 09:35 UTC

**Comment by trevorchill** [comment] 2015-02-01 06:56
I have been having this issue as well. Each time I send a transaction, it works fine. Then I reopen breadwallet later and see that the last txn was unverified, and after it finishes syncing, the txn disappears. But it was confirmed in a block long before. 

I'm then forced to rescan the blockchain to force it to see the last transaction...  If this keeps happening I'll have to stop using it.
