### ISSUE TITLE
Support restoring 15, 18, 21, 24 word phrases

### ISSUE THREAD

**Issue by dabura667** [voisine/breadwallet#155] opened 2015-02-22 06:08 UTC
While in practicality, no wallet supporting m/0'/0/0 is generating non-12 word phrases, the BIP39 states that 12 - 24 word phrases and any multiple of 3 in between are all valid, yet they are not supported for restoring.

**Comment by voisine** [comment] 2015-02-22 20:47
Thanks @dabura667, I'm going to mark this as a dupe of #131 to try to keep all the discussion about importing seeds from other wallets in one place.

**Closed by voisine** 2015-02-22 20:47 UTC
Labels: duplicate
