### ISSUE TITLE
Generating transaction using empty output, even after complete rescan.

### ISSUE THREAD

**Issue by Transisto** [voisine/breadwallet#349] opened 2016-02-06 03:20 UTC
https://i.imgur.com/nzjrm6y.png

The transaction is using 3 address, 2 or 3 of which were empty, Like : 12keeocyBEWr2jHwWcry8zfmccSHNWPqBB
https://blockchain.info/address/12keeocyBEWr2jHwWcry8zfmccSHNWPqBB

I told the customer to restore his backup... PITA

**Comment by Transisto** [comment] 2016-02-06 03:24
Funds became available again after a complete rescan (that took 40 min), but the transaction that we made after was the same with the same problem.

**Comment by voisine** [comment] 2016-02-06 19:15
I don't understand what "using empty output" means. Do you mean you're generating a transaction with an OP_RETURN output script?

**Comment by Transisto** [comment] 2016-02-06 19:17
it mean the transaction never get relayed and when checking on bc.info the 4 address that are being used to send the bitcoin, 3 out of 4 are empty, so no wonder the transaction is not relaying.

**Comment by voisine** [comment] 2016-02-06 19:22
I see, so the wallet appears to be missing transactions. Can you have the customer contact support@breadwallet.com so we can investigate further?

**Comment by juscamarena** [comment] 2016-02-07 00:05
Hey, I had this issue too with the latest version. I believe I commented on here, but this was exactly what was happening to me.  Only 1 address actually had money and the rest of the addresses didn't. I had to go back to an older version and that one detected everything correctly.

**Comment by trevorchill** [comment] 2016-02-19 03:42
I bet this is a duplicate of #326.

**Comment by voisine** [comment] 2016-02-23 23:57
merging this with #326.

**Closed by voisine** 2016-02-23 23:57 UTC
Labels: duplicate
