### ISSUE TITLE
Automatically calculated fee is way too low

### ISSUE THREAD

**Issue by seweso** [voisine/breadwallet#354] opened 2016-02-29 16:35 UTC
My transaction is still not confirmed after 2 hours 3 minutes. Fee was set at 6000 satoshi for 226 bytes, when it should have been at least 60 satoshi per byte (13560).

**Comment by voisine** [comment] 2016-03-05 20:09
We're currently at 26 satoshi per byte. This is still getting typical confirmation times of 2-3 blocks for less that half the rate your'e suggesting. Going to 60 might get you in one block sooner on average, but at the cost more than doubling fees. I'm not convinced that's a good tradeoff.

**Comment by netknokt** [comment] 2016-03-17 12:52
How are you calculating fees? Is the bits/kb hard coded, or is it calculated based on recent block fees?

**I'd really like to see an option to set the fee calculation by percentage of transaction amount**. I think a default of .2%-.5% is sensible. This calculation can use the recent block fees/kb as a lower bound and can use 10-15 USD in BTC as the upper bound. (slightly less than wire transfer fees)

Of course, there's no way to enforce this fee level on the network, so a bit of social shame would be necessary. 

This option would be called, "**Fair Fee**" and described as proportional to amount transferred, so users that transfer larger amounts get a higher chance of confirmation priority if there is network congestion and also pay a more fair share of the value being exchanged to secure the network. It should be especially encouraged when using BTC to transfer value across national borders, because users are truly getting a great service when using it for this purpose, and these transfers tend to be on the large side frequently as well.

The other option would be called "**Minimum Fee**" with the caveat that it's subject to more randomness in confirmation times if the network is experiencing congestion. (Which is invisible to the user so they can't know in advance unless they go look at a block explorer website or the outstanding unconfirmed transaction bytes waiting to get into the next block.)

I know this might sound fluffy, and it is, but I believe that its useful going forward, especially as the block subsidy declines this year, and again in 4 years.

I also personally would use "Fair Fee" in certain circumstances, because I understand the ramifications and benefits of paying a little more, and the fact that bitcoin can't really be free/cheap, and the more fees paid, the more hash power will be applied to mining.

Blocks are now regularly moving 20-30M USD in bitcoin. Those users moving 3000USD and higher can truly pay 10-15 USD without blinking, and it's good for the ecosystem.

thanks for listening

**Comment by voisine** [comment] 2016-04-03 05:56
The fee is based on satoshis-per-kb, based on the minimum fee rate required for the smallest possible tx to get into eligius pool, which supports child-pays-for-parent. This also happens to be a reasonably decent fee rate when targeting 2-3 block confirmation times. It can however be bumped up within a hard-coded range based on our fee api if network conditions change rapidly before we can get an update out.

Basing the fee as a percentage of the amount isn't something we're likely to do since no miners/pools we've been made aware of consider this in their tx selection, apart from the small portion of each block set aside for high-priority tx. Previously it was not uncommon to pay no fees at all on large amount tx, taking advantage of the higher priority these tx generally have.

Additionally we intend to do everything we possibly can to avoid the need to force users into making extra decisions when sending a transaction. If there's a choice that's possible to get wrong, lots of people will get it wrong.

The solution to declining block rewards is to massively increase bitcoin adoption, which will mean massive increase in the number of transactions: total_fees = average_fee_per_tx * number_of_tx

the highest revenue businesses are consistently the ones that go for low price, high volume

**Closed by voisine** 2016-04-03 05:56 UTC

**Comment by seweso** [comment] 2016-06-15 15:18
Have not seen this problem since. No problem sending transactions during the current backlog.

**Comment by voisine** [comment] 2016-06-15 23:11
bip133 is implemented for bitcoind 0.13, and we added support in breadwallet with d08695b

The app will automatically bump up fees if the peers it's connected to all send feefilter messages with a higher fee rate than the app is currently using.

**Comment by voisine** [comment] 2016-06-15 23:18
As an aside, looks like the latest incarnation of child-pays-for-parent is close to getting merged:

https://github.com/bitcoin/bitcoin/pull/7600#discussion_r67177283

**Comment by seweso** [comment] 2016-06-16 15:36
Nope still way too low. Can't even use ShapeShift this way, as it shows "Time remaining expired". 

https://blockchain.info/tx/e786c4e3c5b0843f2c192ccaed591b28f86fa251cffe77a174c7a294a2463f5e

If I can't select a fee, then at least make sure the automatic fee is high enough at all times. This makes Bread-wallet completely unusable.

**Comment by dabura667** [comment] 2016-06-16 15:55
Targetting "a reasonable confirmation time" doesn't really work when the merchant is expecting "a confirmation in at least 15 minutes."

Maybe merchants (and shapeshift) should extend their timeouts.

**Comment by dabura667** [comment] 2016-06-16 15:57
But yeah, targetting "getting in the next block" always is basically the "expected behavior" of bitcoin for users.

Savings on fees are miniscule compared to the trouble they can cause ie. "user wastes time contactingg support at merchant etc... And time is money"

**Comment by voisine** [comment] 2016-06-16 16:51
@seweso, your tx confirmed in just over one hour. That's normal variance. It will happen from time to time no matter what fee you pay.

What is shapeshift doing? They cancel your trade if it takes over an hour to confirm or something?

**Comment by seweso** [comment] 2016-06-17 09:25
ShapeShift canceled my transaction yes.  And it wasn't variance, my transaction skipped about 9 blocks. Don't know if I need to create a ticket with them, because they can see the canceled transaction.

But Eth is down now, so I came out ahead. 

First I won 0.5 BTC, which was sponsered by Breadwallet. And now because Breadwallet gave a low fee, which canceled my exchange to ETH. And I went all-in...

**Comment by voisine** [comment] 2016-06-17 09:51
@seweso, 9 blocks is easily still due to variance even if 2 to 3 is more typical. When there is long time between blocks, it can take several more to clear out a backlog, and miners can always still chose which valid to to include or not according to any criteria they want. They can and often do even make empty blocks.

9 blocks and an hour to confirm is not as good as we'd like to see on average, but can still happen on occation now matter what fee is paid.

**Comment by dabura667** [comment] 2016-06-17 10:06
to be specific, it took 1 hour 15 minutes and 6 blocks passed before getting confirmed on the 7th block.

blockcypher api logs "first seen" on all transactions and blocks, so it's easy to calculate this stuff in retrospect.
