### ISSUE TITLE
Dynamic fee estimation

### ISSUE THREAD

**Issue by bamos01** [voisine/breadwallet#267] opened 2015-09-07 02:27 UTC
Have you considered using a service like blocktrail or cointape to dynamically estimate the optimal tx fee?  I am confused about how the tx fee is estimated- it seems like it would be better to add a few satoshis when there is more congestion rather than risk excessive delay.  I am sure you have considered this but interested in your thoughts.  thx

**Comment by voisine** [comment] 2015-09-07 02:41
We're trying to balance fast confirmation times with low, stable, predictable fees. We allow spending unconfirmed inputs, so from the user's perspective, all transactions appear instant even if they take a while to confirm. With capped block space, merchants and services will have to adjust to the reality of unpredictable confirmation times. Raising fees will fix the problem for breadwallet users only temporarily until all the other wallets do the same. As long as demand for blockspace isn't constant and uniform, then  confirmation times can't be either when there's a fixed production quota.

dupe of #251

**Closed by voisine** 2015-09-07 02:41 UTC
Labels: duplicate

**Comment by bamos01** [comment] 2015-09-07 22:22
Thanks for reply. Makes some sense but I wish there was a better solution-
not having a transaction confirm still negatively impacts user experience
and some option that allows for dynamic fees may be better for the user
than having to wait a long time for the confirmation.

**Comment by voisine** [comment] 2015-09-07 22:54
This is a subject that keeps coming up. I'd really like to better understand the motivation behind the desire to have really quick confirmation times. So far every person who's complained has mentioned gyft specifically as their reason for wanting fast confirmation. Is that your situation as well, or is there some other reason you need it? Once you are in a position of needing confirmation, you are no longer dealing with a near instant real-time transaction, so having to wait 5-20min typically vs an hour doesn't seem like much of a difference once you're in the mode of sending and coming back to check on it later.

**Comment by bamos01** [comment] 2015-09-07 23:22
Definitely other merchants follow this policy of not crediting the order
until there is confirmation. I was trying to buy dinner tonight on foodler
but they wouldn't give me the credit until confirmation of transaction.
Makes a difference to have it confirm within 10min. Agree not a huge
difference if 20min. But if it starts being more like an hour it is
disconcerting.

**Comment by voisine** [comment] 2015-09-07 23:28
fair enough, a restaruant check where you’re used to waiting 10-15min for the wait staff to shuttle your bill/credit card back and forth a few times is a situation where a short confirmation time makes a difference. I’ll just point out that it can take an hour on occasion even with no network congestion due to the random distribution of block discovery, and also this payment experience is fairly north america centric. In japan for instance you pay at the reception desk as you walk out.

**Comment by bamos01** [comment] 2015-09-08 00:15
I guess the real issue is whether merchants will accept zero conf
transactions. It seemed like they were for awhile but now some have stopped
(eg Gyft). I guess if zero conf transactions can't be accepted safely then
we are going to need some other kinds of fixes before Bitcoin can be used
easily for day to day transactions.

**Comment by voisine** [comment] 2015-09-08 03:47
As the industry matures, payment processors and zero-conf confidence services I think will evolve into insurers. double-spend rates with bitcoin are much lower than fraud and chargebacks with credit cards already, but that risk will eventually become measured, well understood and insured against.

**Comment by keo** [comment] 2016-02-01 15:11
Hi,

I have this problem as well. Would be great to be able to send a high priority transaction (I liked the "Rush" idea from the other thread. When sending a transaction, let me choose High Priority somehow right on the payment screen).

My use case: I am moving money from my wallet to my Xapo debit card. Xapo requires 6 confirmations so I can use it.

I'm waiting for an hour now, 6 new blocks have already been mined since and mine is still unconfirmed.
And the shop closes in 1 hour... It's really depressing to see all these filled up blocks and not being able to do anything.


Thanks for listening :)

**Comment by keo** [comment] 2016-02-15 18:52
Here's another use case - a problem we have as breadwallet users, and also customers of our ATM have the same issue.

When withdrawing cash (ie. selling BTC at the BTM), you have to wait 1 confirmation to get your cash. Before the blocks got full, this was 5-10 minutes at most.

Now as a breadwallet user you have to wait hours for the tx to confirm, and msny ATMs have a redeeming timeout. So if your tx gets stuck, and it takes more than 6 hours to be included in a block (timeout for Lamassu ATMs that you cannot change), you have to call the operator so they sort it out by hand.

This is really annoying, and a very valid (and painful) usecase right now.

**Comment by keo** [comment] 2016-02-15 18:53
The point is, being able to send high-priority transactions would be awesome. There's many sites out there that provide great fee estimates for low, medium and high prio transactions.

**Comment by voisine** [comment] 2016-02-15 19:06
@keo I can see how that's really problematic.

We can certainly bump fees to improve this in the short term, but with full blocks this is going to be a persistent problem no matter what we do.

We may end up using our fee api endpoint to try to get a better user experience, as fees are already confusing enough that few people understands them, so having them change apparently randomly won't make it too much worse than it already is.

All that said, ATM operators are going to have to start accepting that timely confirmations just aren't a realistic thing they can rely on anymore. That's not how the bitcoin network works anymore. They're going to have to get more sophisticated about predicting what transactions are likely to confirm.

**Comment by keo** [comment] 2016-02-19 00:02
Well, having a "rush" or "high priority" option when paying would be really great. That would solve it.

Or a buried advanced setting which you can turn on a case by case basis, if you don't want to show the "Rush" option for everyone, always.

As an ATM operator we accept high confidence zero-conf transactions under $70, but for higher value transactions we have to wait a confirmation.

**Comment by keo** [comment] 2016-03-02 10:41
> All that said, ATM operators are going to have to start accepting that timely confirmations just aren't a realistic thing they can rely on anymore. That's not how the bitcoin network works anymore. They're going to have to get more sophisticated about predicting what transactions are likely to confirm.

Now that the network started to get _really_ congested, we have transactions that take 24-36 hours to con confirm. For higher value transactions it simply doesn't work to accept the zero confirmation transction in the ATM - the only thing we could do is say that the fiat withdrawal limit is $100. Which makes the ATM pretty useless.

There's unfortunate guys, such as those who use Xapo or CIrcle - where they have no control over the fees... And Xapo typically uses lower fee per kB, and their transactions get stuck for many hours, even an entire day. Let's not do the same with breadwallet :)

It would be great if you guys could bump up the per kB fee on your server, or maybe even use a dynamic fee from https://bitcoinfees.21.co/api or similar. With 26 satoshi / byte, the confirmation times usually ends up being a few hours.

(for outgoing transaction on our ATM and online exchange we already bumped up the fees, because our customers usually use them to load debit cards or to deposit the bitcoins to another exchange for buying alts... So they need the confirmations unfortunately)
