### ISSUE TITLE
Add iPhone 6/6 Plus native resolutions

### ISSUE THREAD

**Issue by leoncfu** [voisine/breadwallet#115] opened 2014-12-02 05:16 UTC
The app does not support iPhone 6/6+ native resolutions. It would be nice to have instead of the 4" layout scaled up to the larger screens. Also, any plans for iPad UI?

**Comment by malishev** [comment] 2015-11-20 21:39
Is it possible to use the same layout for both iPads and iPhones?

Right now breadwallet looks like this (clickable):

[![img_2925_prev](https://cloud.githubusercontent.com/assets/2178368/11312375/9f20cd4c-8fe6-11e5-8946-46c0ff34103d.jpg)](https://cloud.githubusercontent.com/assets/2178368/11312169/87aee82a-8fe5-11e5-8820-0600c770e4a4.PNG)

It is usable, but not very convenient because of the huge black frame.

What am i proposing: using the same layout, but stretched on the whole screen, like [in this app](https://itunes.apple.com/ru/app/andeks.kluc/id957324816):

[![img_2926_prev](https://cloud.githubusercontent.com/assets/2178368/11312332/850e4556-8fe6-11e5-8faa-627fdd2cf29a.jpg)](https://cloud.githubusercontent.com/assets/2178368/11312243/f81d7a54-8fe5-11e5-950f-4dfa2e3da457.png)

This app uses the same layout for all devices. It sometimes looks strange on large screens, but this is definitely better than black frame.

Moreover, seems like this won't take much coding time.

**Comment by voisine** [comment] 2015-11-20 21:54
iPads right now aren't a very portion of our users (something like 2%). We do support native iPhone6/6+ resolution now. It will be in the next update. For iPad the plan is to eventually have a merchant specific version, since we think that's the most likely use case for an iPad.

**Closed by voisine** 2015-11-20 21:54 UTC
Labels: enhancement

**Comment by malishev** [comment] 2015-11-20 22:30
This is the funny thing: there are no iPad users because bread wallet doesn't support iPads, so AppStore doesn't display it in search results. You just cannot install it unless you follow direct link to AppStore.

Anyway, got your point, will use something else.

**Comment by voisine** [comment] 2015-11-20 22:54
That's a fair point, but I think the dominant issue is that not so many people want to whip out their iPad to make a payment. For the few who do, breadwallet still works just fine, albeit with a scaled UI. We want so support iPad better, but I'd rather do it the right way by designing a UI specifically for the use cases that make sense for that form factor.

Let us know what you end up using. I'm not aware of any other user easy to use SPV wallets for iOS. If you find one, I'm sure we can learn from it.
