### ISSUE TITLE
Dependency on blockchain.info

### ISSUE THREAD

**Issue by JustinDrake** [voisine/breadwallet#130] opened 2015-01-06 09:28 UTC
The readme states:

```
breadwallet is a real standalone bitcoin client. There is no server to get hacked or go down
```

Technically, Breadwallet has at least two dependencies, namely the blockchain.info ticker, and their API to query for unspent outputs.

If, for example, the ticker gets hacked, then users can be fooled into sending more money than they should be sending.

**Comment by voisine** [comment] 2015-01-07 03:08
Thanks @JustinDrake. I agree and we need multiple sources for exchange rate data. (utxo as well, but that isn't used for wallet funds, only sweeping private keys not yet in your wallet)

I'm gonna close this as a dupe of #57 since this issue is discussed there

**Closed by voisine** 2015-01-07 03:08 UTC
Labels: duplicate
