### ISSUE TITLE
Request: Display of bitcoin standard.

### ISSUE THREAD

**Issue by RichardStott** [voisine/breadwallet#270] opened 2015-09-08 22:33 UTC
First, this is an excellent wallet. The BEST on the market hands down. VERY impressed!

Second, would it be possible to display "normal" bitcoin amount in settings?

1BTC = 1.00, 

I get very confused with bits...

Thanks again, and keep up the great work!!!!!!

**Comment by voisine** [comment] 2015-09-08 22:49
Thanks @RichardStott, we love our users! :)

We feel strongly that the community needs to all switch together to the bits denomination standard. We understand of course that nobody likes change. It's a real pain, but if we don't switch we will hold back bitcoin adoption by confusing new users. That's why we're helping to drive the switch. Bits have two decimal places like nearly every other currency, and will continue to work fine even when bitcoin eventually replaces all currencies in the world. Switching will only get harder as the community grows, so that's why it's important to take a relatively small amount of pain now to make it happen.

dupe of #29

**Closed by voisine** 2015-09-08 22:49 UTC
Labels: duplicate

**Comment by RichardStott** [comment] 2015-09-08 22:54
Great response.

This is very true. Keep up the good work! I'm backing bits!

Richard Stott
Design Director
--
Tel: +44(0)798 555 8590
Email: richard@proofofwork.media
Skype: phenotype001​ Twitter: @cablestudios
http://keybase.io/cablestudios​
https://onename.com/cablestudios


proofofwork.media @proofofwork
ProofofWork.meida ltd
150 City Rd, London, EC1V 2NL, UK
Registered in England and Wales, Registration Number - 09146801

This e-mail and any file transmitted with it are confidential and intended solely for the use of the recipient(s) to whom it is addressed. Dissemination, distribution, and/or copying of the transmission by anyone other than the intended recipient(s) is prohibited. If you have received this transmission in error please notify ProofofWork ltd immediately and delete it from your system. E-mail transmissions cannot be guaranteed to be secure or error free. We do not accept liability for any loss, damage, or error arising from this transmission.
