### ISSUE TITLE
Sudden double spend

### ISSUE THREAD

**Issue by karek314** [voisine/breadwallet#298] opened 2015-10-29 20:32 UTC
As title says, sometimes wallet send duplicated transactions and one of them is interpreted as double spend. Latest appstore version.

**Comment by voisine** [comment] 2015-10-29 20:41
Thanks @karek314, this is actually not being sent from the wallet, it is what's called a transaction malleability nuisance attack. Any node on the bitcoin network can create a duplicate of your transaction with a slight change to the way the signature is encoded, and it will have a different transaction hash, so show up as separate transaction that is a double spend of the first. There is an update to the way that bitcoin nodes behave by default (modifying all transactions to a standard form before relaying them) that should largely fix the issue over the coming months. In the mean time, your funds are secure and you should not see any problems sending or receiving since breadwallet correctly marks double spends as invalid.

**Closed by voisine** 2015-10-29 20:41 UTC
