### ISSUE TITLE
Frequent "transaction canceled".

### ISSUE THREAD

**Issue by ejhong** [voisine/breadwallet#312] opened 2015-11-24 23:14 UTC
I've been getting this pretty frequently about the last two weeks.

Sometimes it would take a long time for the blue line to move across the top - maybe about 30 seconds, and then the popup would come up saying:  "couldn't make payment.  transaction canceled, network timeout".
Sometimes the blue line goes fast but after about 5 or 10 seconds the same dialog comes up.

Network connectivity was fine at least during some of these occassions.  When it's failing, it will fail repeatedly on several attempts.  Would start working randomly again, I think sometimes after I restart the application.

**Comment by KickedMe** [comment] 2015-11-26 05:10
I've been experiencing the same issue for the past few days now. Sometimes when I try to send a transaction I get that error and I have to retry about seven times for it to finally go through.

**Comment by ejhong** [comment] 2015-11-26 19:30
Happened again yesterday.  It's getting pretty troublesome.

One successful send followed by about 6 unsuccessful sends.  In between the unsuccessful sends, I tried restarting the application but that didn't help.  Then I disconnected from my WIFI (which was fine for other purposes) and let the phone reconnect on the phone data network.  At this point, the send was successful.

If this continues, I may try to wipe the app and reinstall and see if that helps.

**Comment by voisine** [comment] 2015-11-26 22:55
I believe this is fixed in the github version which we're currently testing for app store release. @ejhong @KickedMe, email me your iTunes account email address and we can invite you to the testflight beta so we can verify it's fixed for your specific case.

**Comment by ejhong** [comment] 2015-11-26 23:53
Have installed it and so far so good. Will report in a few days.

**Comment by ejhong** [comment] 2015-11-30 04:00
Looking good so far.

**Comment by Logicwax** [comment] 2015-12-16 04:04
I've been having the exact same problems ever since the stress testing began this year, around the september/october time-frame.   I repeatedly have to keep shutting down the application and restarting it till it finds some "good" network nodes that won't reject my transactions.   I'm thinking this has to do with low fee amounts.    This problem exists with anyone else I know who runs Breadwallet.  Can there be some option added to allow manual over-ride of fees?    

also, it would be nice to allow manual selection of a trusted node.  Android bitcoin client allows this as well.  Very useful if you run your own full node. 

Unfortunately, it's really hurting the image of Breadwallet when I tell people to use it, then have it sit there stalling until after three or four reboots of the application.    FYI: Once a "friendly" node is found, the application will have no problems sending transactions while it's kept open.   I can send 5, 6, 10 transactions without a hitch.   It's all a game of getting it to connect to "friendly" nodes I guess.

**Comment by ejhong** [comment] 2015-12-16 04:30
Beta continues to work very well for me - no issues with canceled transactions.

**Comment by voisine** [comment] 2015-12-16 19:28
@Logicwax sorry you're experiencing that issue. Does it happen every time? 

It can happen with the current app store version in an edge case. The sudden an uncoordinated change in the default minimum relay fee by bitcoin core also had the unfortunate side effect of changing the output amount considered to be "dust". We pay high enough fees for all tx to get relayed, but if the change amount from your transaction happens to be between the old dust output amount and the new dust output amount, your tx will get rejected by nodes running the updated policy.

The new version of breadwallet will adjust the dust calculation along with any fee rate changes, and will also avoid nodes that have unexpected relay rules.

**Comment by Logicwax** [comment] 2015-12-17 06:23
yes....it's about a coin-toss every time I open up Breadwallet (about 3 times a day).   Sometimes I'm lucky and it works right from the start....and I can keep sending and sending no problems.  Other times....I'll have to completely shut it down and re-open it several times till it grabs a "friendly" node.


I don't have access to the beta, so I cannot test.    When is it expected to hit the appstore?

**Comment by voisine** [comment] 2015-12-17 23:13
If you like, we can invite you to the testflight beta. Email me your iTunes account email address and we can add you. My email is in the LICENSE file.

**Comment by kmil12** [comment] 2015-12-20 15:36
Can I please get the beta too? I am unable to send any funds. Failing 100% of the time.

**Comment by dabura667** [comment] 2015-12-20 16:07
@kmil12 New version just came out today. Have you updated and tried it?

**Comment by kmil12** [comment] 2015-12-20 16:10
I have 0.5.3 and no updates are showing. Is that the most recent?

Mike

iPhone, iTypo, iApologize.

On Dec 20, 2015, at 9:07 AM, dabura667 <notifications@github.com<mailto:notifications@github.com>> wrote:


@kmil12<https://github.com/kmil12> New version just came out today. Have you updated and tried it?

-

**Comment by kmil12** [comment] 2015-12-20 16:24
Never mind, downloaded and reinstalled and we are good to go.

Thanks,

Mike

iPhone, iTypo, iApologize.

On Dec 20, 2015, at 9:07 AM, dabura667 <notifications@github.com<mailto:notifications@github.com>> wrote:


@kmil12<https://github.com/kmil12> New version just came out today. Have you updated and tried it?

-

**Closed** 2015-12-20 17:56 UTC

**Comment by Logicwax** [comment] 2015-12-21 17:46
Got the new version the other day from the AppStore.   Tried many transactions of $0.25.   Only had one failure.   So it sounds like it's pretty much 98% fixed.        

Love the high-tea scaling on the new version too.   Would be nice to have better pop-up notification when paying/receiving than a tiny grey box that vanishes really quick.    I also noticed the app isn't searchable from spotlight anymore.   So if you don't know where it's on your phone...you won't be able to search for it.

**Comment by voisine** [comment] 2015-12-21 20:24
I will have to look into the spotlight issue. In the mean time you can get even quicker access by enabling the today extension.

When you tried many transactions, did you get up to 25 of them? There's a new mempool limit recently added on full nodes for the length of chains of unconfirmed inputs, limited to 25. We can mitigate that problem by change splitting, but that's not implemented yet.
