### ISSUE TITLE
Transaction confirmation problem

### ISSUE THREAD

**Issue by trevorchill** [voisine/breadwallet#326] opened 2015-12-23 03:53 UTC
I have had a repeated problem with transactions in my history. Right now, my latest transaction that has more than a hundred confirmations shows as unverified in the client. 

When I try to rescan, the rescan is almost instant and it doesn't really rescan or fix it. Recently I had a similar issue and had to delete the wallet and re-enter the pass phrase to reconstitute it - only that worked to fix the problem, but then I did a single further transaction to transfer the entire balance to an external address and that transaction is having the same problem. 

It first shows as unverified. Then after a couple of seconds, it prompts me to rescan and the transaction disappears from the history. Then I try to rescan and the rescan is just a blip, and the transaction reappears as unverified again.

**Comment by trevorchill** [comment] 2015-12-23 04:01
Also, I think there may be a problem with two things that may have led to this.  

First, receiving payments to a previously used address.

Second, sending transaction A and closing the app before confirmation, then receiving transaction B while the app is closed, then reopening the app before either A or B are confirmed.

Not sure if these are relevant but I sort of thought I noticed the weirdness occurring after these scenarios.

**Comment by voisine** [comment] 2015-12-23 04:06
Using a previously used address should have no effect.

I think I have a wallet that's demonstrating the rescan issue, investigating...

**Comment by voisine** [comment] 2015-12-23 04:42
Okay, so looks like the temporary workaround if rescan isn't working is to delete and reinstall the app. Your wallet keys will not be erased, but it will resync. :-/

**Comment by trevorchill** [comment] 2015-12-23 05:20
Any idea why my transactions are showing as unverified when they've been confirmed?

**Comment by voisine** [comment] 2015-12-23 06:02
That I haven't been able to observe yet. Still investigating. It's not a case of tx malleability is it? Does the unverified tx id match what's confirmed?

**Comment by trevorchill** [comment] 2015-12-23 11:13
I copied the txid from the history and searched it on some explorers so it seemed to be correct.

**Comment by trevorchill** [comment] 2015-12-23 11:15
One other tidbit - each time I entered the history to view the transaction list, I noticed that the time of the unverified transaction was listed as the present time, not the time it was actually made.

**Comment by trevorchill** [comment] 2015-12-26 08:43
Since the unverified transactions problem is the main issue here, I don't think this should be closed. I just experienced the exact same thing yet again.

**Comment by voisine** [comment] 2015-12-26 20:38
good point

**Comment by trevorchill** [comment] 2015-12-27 04:50
Could it be that when I sent my full balance and the dialog allows me to change the amount by deducting the fee, that internally the amounts are not tracked correctly leading to a mistake in recognizing the transaction?  Is it looking for a transaction without that fee deducted?  Or something like that...?

**Comment by trevorchill** [comment] 2016-01-15 01:49
This seems to happen consistently when I spend the entire balance of my wallet and then agree to deduct the required fee from that amount, leaving a zero balance in the wallet.  It correctly sends the transaction, but then upon opening the app the next time, it says the transaction was rejected (which it hasn't been).

Re-scanning still doesn't fix it unless I re-download the app and then rescan.  Then it finally corrects.

**Comment by voisine** [comment] 2016-01-15 01:53
Do you have the newest v0.5.4? That should correct the rescan issue. 

That's good feedback on how to reproduce it. I will see if I can get it to happen.

**Comment by trevorchill** [comment] 2016-01-15 01:59
Yes, I have the newest version.  Rescan seems to work better but doesn't seem to fix this issue yet without reinstalling...

**Comment by Onetallnerd** [comment] 2016-01-23 05:31
I'm having this issue too on the latest version. Rescanning does not work. I will attempt to delete and reinstall. Is there anyway I can connect breadwallet to my own bitcoin node? My transaction is not being seen by any peers.

**Comment by Onetallnerd** [comment] 2016-01-25 08:15
I tried another device and it does not work on the latest update. I had to go back to one of my siblings phones on an older version of breadwallet and restored my seed and that one actually interpreted the balance correctly and send the money and confirmed just fine! (it also had lower fees ;P)

**Comment by voisine** [comment] 2016-01-25 22:42
hmm... @Onetallnerd do you have 0.5.3 or 0.5.4? Your issue sounds like it could happen with 0.5.3.

**Comment by Onetallnerd** [comment] 2016-01-26 04:28
v0.5.4

**Comment by jguchte** [comment] 2016-04-26 10:51
@trevorchill 
Same problem here when I spend the entire balance of my wallet and then agree to deduct the required fee from that amount, leaving a zero balance in the wallet.

"Transaction rejected". Now rescanning the blockchain.

**Comment by voisine** [comment] 2016-05-06 20:00
This is resolved with f37d19c, @jguchte or anyone else who needs a fix immediately rather than wait for the forthcoming app store update, please contact support@breadwallet.com

**Closed by voisine** 2016-05-06 20:00 UTC
