### ISSUE TITLE
0 confirmations after 15 hours, rescanned 3x and recovered wallet to no avail

### ISSUE THREAD

**Issue by jbreuch** [voisine/breadwallet#234] opened 2015-07-08 18:47 UTC
Im attempting to send a single transaction out of my wallet, but it has been over 15 hours and I haven't received any confirmations, and none of the techniques offered to aid this process are helping. I have rescanned the block chain numerous times as well as recovered the wallet, and nothing has worked.  Please offer me some help

**Comment by jonasschnelli** [comment] 2015-07-08 19:04
@jbreuch: at the moment there are many unconfirmed transaction because of a very hight volume in transactions (some people decided to flood the nodes mempool a.k.a. DOS attack).
During the time of writing, there are around 80'000 unconfirmed transactions (https://tradeblock.com/blockchain/).

The mempools are now around 81MB which means to work this down it might take around 17h. But new transaction are coming in, probably with higher fees. So prepare yourself to wait >24h.

The problem is, that users can't change the fee when they have made and broadcastet a transaction. Most wallet application need to change their approach of handling unconfirmed transaction (FSS-RBF or CPFP). Increasing your fee to the current market situation might result in a confirmation <20min.

**Comment by voisine** [comment] 2015-07-08 23:32
@jbreuch, yes @jonasschnelli is correct. The bitcoin network is now reaching capacity, so long and/or unpredictable confirmation times are going to be something users will have to learn to adjust to.

Breadwallet allows you to spend unconfirmed transaction you receive, so the day-to-day usability is not really be much different. We will also be increasing default transaction fees to compensate, but this won't help if people continue to submit new transactions with even higher fees afterward. The way people have come to know an love using bitcoin is going to change for the worse, but we are committed to doing everything we can to give users the best experience possible under these difficult circumstances.

**Comment by OtisTyler** [comment] 2015-07-09 00:23
Has a variable or user set fee been considered?  I don't want to continue sending high fee transactions if the backlog of unconfirmed transactions clears out.

**Comment by voisine** [comment] 2015-07-09 00:44
@OtisTyler yes, we will have dynamic fees so that you pay based on current network congestion, as well as a higher default fee that hopefully will work most of the time so that you don't have to trust and rely on external services to inform your wallet about current network conditions.

**Comment by smokebox46and2** [comment] 2015-07-13 03:06
Aaron, are you in favor of a block size increase as the method to return bitcoin to favorable conditions?

**Comment by voisine** [comment] 2015-07-13 03:47
@smokebox46and2 Yes, I've expressed my views on the blocksize limit on the development mailing list. 

You want to control blockchain use with fees, rather than controlling fees with a fixed max blocksize.
Trying to control fees with a fixed production quota is disruptive. You want to encourage users to voluntarily economize on blockchain use with the same tested and safe ways that fees have been implemented all along, with minimum relay fees and transaction selection rules for miners that deprioritize low fee transactions without dropping them.

**Comment by smokebox46and2** [comment] 2015-07-13 03:57
Agreed.  But you don't think there is a good chance of returning to this?  The current situation is very unwelcoming to those new to bitcoin and disappointing to us veteran users.  i just can't believe there are those who don't see this as a problem.

**Comment by voisine** [comment] 2015-07-14 00:20
Several important people seem to think a fixed max blocksize is the right way to create a "fee market". This seems obviously backwards to me. You want fees to create a market for blockchain space instead. I hope sanity wins out, but we'll do everything we can to create the best user experience possible in either case.

**Closed by voisine** 2015-07-14 00:20 UTC

**Comment by smokebox46and2** [comment] 2015-07-14 00:55
right on, Aaron.  seems obvious to me as well.  here's to hoping.  thanks for your hard work.

on the other thread regarding the limbo TXs, when a TX is dropped from the mempool do the funds show up in breadWallet as the UTXOs they were (balance restored), or how does breadWallet represent a dropped TX?
