### ISSUE TITLE
No keyboard when confirming transactions

### ISSUE THREAD

**Issue by thegus4** [voisine/breadwallet#198] opened 2015-05-06 15:55 UTC
When I pay, wether I accept or reject fee, I am asked for passcode, without a keyboard, and the only option I have is to cancel. Therefore, I cannot send any payments.

Iphone 4S ios 7.1.2

Thanks!

**Comment by voisine** [comment] 2015-05-06 16:41
This bug is specific to iOS 7, I think you can get around it by turning off the remove fee option in settings for now. It's fixed for the next update.

**Comment by thegus4** [comment] 2015-05-06 19:34
Thanks!

**Comment by voisine** [comment] 2015-05-06 19:44
closing as dupe of #180

**Closed by voisine** 2015-05-06 19:44 UTC
Labels: duplicate
